services:

  localstack:
    container_name: "authorizer-localstack"
    image: localstack/localstack
    ports:
      - "9000:8080"
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DEBUG=1
      - SERVICES=sqs,dynamodb
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=38dc4428-dc4e-4703-b861-3d15454b2c14
      - AWS_SECRET_ACCESS_KEY=2c6ece77-f3c9-42ff-84b4-57db266ad21f
      - AWS_DEFAULT_REGION=sa-east-1
      - LOCALSTACK_VOLUME_DIR=/var/lib/localstack
      - INIT_SCRIPTS_PATH=/etc/localstack/init/ready.d
    volumes:
      - "./configuration/localstack/init.sh:/etc/localstack/init/ready.d/init-aws.sh:ro"
    networks:
      - authorizer-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

networks:
  authorizer-network:
    driver: bridge
