spring:

  cloud:

    aws:
      region:
        static: sa-east-1
      credentials:
        access-key: 38dc4428-dc4e-4703-b861-3d15454b2c14
        secret-key: 2c6ece77-f3c9-42ff-84b4-57db266ad21f
      dynamodb:
        endpoint: http://localhost:4566

    stream:

      kafka:
        binder:
          brokers: "localhost:9092"
          producer-properties:
            schema.registry.url: http://localhost:8081
          configuration:
            schema.registry.url: http://localhost:8081

        bindings:
          transactionExecutedEvent-out-0:
            producer:
              configuration:
                schema.registry.url: http://localhost:8081
